// <auto-generated />
namespace App.FDP
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixStadiumModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixStadiumModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201509272336453_FixStadiumModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
